### ISSUE TITLE
Example of `--override-input`

### ISSUE THREAD

**Issue by srid** [nix-systems/nix-systems#1]
Could you add an example of using this with `--override-input` (i.e., without. modifying the `flake.nix` with "follows" and such) to specify a custom list of systems in the command line.

cf. https://github.com/srid/haskell-template/pull/97

**Comment by srid** [comment]
I feel like since this will require `flake = false;`, it then becomes an argument for creating `github:flake-systems/x86_64-linux` and so forth? This way there is no need to create the `systems.nix` file; and we can just point to the github repo. What do you think @zimbatm ?

```sh
# No need to create a file, and mark 'systems' flake as non-flake.
nix flake check --override-input systems github:flake-systems/x86_64-linux
```

**Comment by srid** [comment]
Also, too bad we can't do this:

```sh
bash-5.2$ nix --option sandbox false flake check -L --override-input systems path:<(echo '["x86_64-linux"]')
error (ignored): error: end of string reached
error: file '/dev/fd/63' has an unsupported type 
(use '--show-trace' to show detailed location information)
```

**Comment by zimbatm** [comment]
https://github.com/numtide/flake-systems/commit/38b3cf5664a5921a7ec3381c84f8094a5110a04a , but as you noted it makes the inputs declaration more complicated. I'm still mulling over that.

**Comment by zimbatm** [comment]
@srid are you holding the flake-systems org? Let's add a few repos in there to test the idea out.

**Comment by srid** [comment]
No. IIRC (I might be wrong) that org didn't exist yesterday. Did someone create it recently?

**Comment by srid** [comment]
No. 

Looks like someone created it on Feb:

```
> http get https://api.github.com/orgs/Flake-systems | get created_at
2023-02-07T08:36:30Z
```

https://github.com/nix-systems is available, though.

**Comment by zimbatm** [comment]
@bb010g maybe?

**Comment by srid** [comment]
Perhaps we can move this repository to`github.com:nix-systems/default`? Then changing systems is only a matter of switching the repo name.
