### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-systems/nix-systems#3]
> Why evaluate all the systems when only using one?

My question: isn't nix lazy and only things get evaluated which are referenced?

> Is the user supposed for fork every flake to add their architecture?

Wasn't ``allSystems`` from flake-utils supposed to fix this?

**Comment by zimbatm** [comment]
In practice, it's easy to make things less lazy than expected. Especially around attrsets as the keys are evaluated strictly. What's missing is real-life examples to make that argument more compelling I think. I know I have seen those in the wild.

Try running `nix flake show` on a flake using `allSystems`.

**Comment by tadfisher** [comment]
flake-utils uses `foldl'` which is strict: https://github.com/numtide/flake-utils/blob/main/lib.nix#L29-L81

If they used something like `nixpkgs.lib.genAttrs` then it would be lazy, and I use that in my flakes with no problems (e.g. I can evaluate `.#packages` for unsupported systems).

> Is the user supposed for fork every flake to add their architecture?

Honestly they should; if a flake doesn't declare it supports a system, then the authors have not decided to support that system. We should encourage contributing code to provide that support, such as PRs to `flake.nix` in addition to all of the other considerations in building and testing for a new platform.
