### ISSUE TITLE
Consider adding defaultLinux and defaultDarwin

### ISSUE THREAD

**Issue by leifhelm** [nix-systems/nix-systems#7]
Some packages may not be available on darwin or linux. Therefore it would be nice to have a dedicated set of the default architectures split by platform. Or in general an easy way of combining for example `x86_64-linux` and `aarch64-linux` without the need to host a new repo.

**Comment by srid** [comment]
Perhaps these could be branches in the default repo.On Apr 23, 2023, at 12:36 PM, leifhelm ***@***.***> wrote:﻿
Some packages may not be available on darwin or linux. Therefore it would be nice to have a dedicated set of the default architectures split by platform. Or in general an easy way of combining for example x86_64-linux and aarch64-linx without the need to host a new repo.

**Comment by srid** [comment]
Perhaps these could be branches in the default repo.

**Comment by dmayle** [comment]
I came here to say the same thing... I support linux right now, and would like to add darwin later, but I have things that I know don't work across both

**Comment by zimbatm** [comment]
We're using repos for each system combination right now. I'm open to adding default-linux and default-darwin repos, which each contain the system tuples.

**Comment by zimbatm** [comment]
@srid do you want to take care of it?

**Comment by srid** [comment]
Done,

- https://github.com/nix-systems/default-linux
- https://github.com/nix-systems/default-darwin

**Comment by zimbatm** [comment]
thanks @srid !
